spring.application.name=votechori-backend
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/votechori?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=80134
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=replace-this-with-a-very-long-secure-secret-key-for-prod
app.jwt.expiration-ms=86400000
app.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173,http://localhost:5174,http://127.0.0.1:5174
